{% set name = "changeforest" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b32dda93d2a6185d2d82836987dc3236304098509a9563d768a43bca96312a7b

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - maturin                                # [build_platform != target_platform]
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - numpy

test:
  imports:
    - changeforest
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mlondschien/changeforest
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Classifier based non-parametric change point detection
  description: |
    Change point detection aims to identify structural breaks in the probability
    distribution of a time series. Existing methods either assume a parametric model for
    within-segment distributions or are based on ranks or distances and thus fail in
    scenarios with a reasonably large dimensionality.

    `changeforest` implements a classifier-based algorithm that consistently estimates
    change points without any parametric assumptions, even in high-dimensional scenarios.
    It uses the out-of-bag probability predictions of a random forest to construct a
    classifier log-likelihood ratio that gets optimized using a computationally feasible two-step
    method.

    See [1] for details.

    [1] M. Londschien, P. Bühlmann, and S. Kovács (2023). "Random Forests for Change Point Detection" Journal of Machine Learning Research
  dev_url: https://github.com/mlondschien/changeforest

extra:
  recipe-maintainers:
    - mlondschien
